import type { Metadata } from "next";
import { Navbar } from "./Components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Feeds | Prisma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mb-6">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
